package com.model;

public class AgentRetailer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_retailer.agent
     *
     * @mbggenerated
     */
    private String agent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_retailer.retailer
     *
     * @mbggenerated
     */
    private String retailer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_retailer.agent
     *
     * @return the value of agent_retailer.agent
     *
     * @mbggenerated
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_retailer.agent
     *
     * @param agent the value for agent_retailer.agent
     *
     * @mbggenerated
     */
    public void setAgent(String agent) {
        this.agent = agent == null ? null : agent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_retailer.retailer
     *
     * @return the value of agent_retailer.retailer
     *
     * @mbggenerated
     */
    public String getRetailer() {
        return retailer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_retailer.retailer
     *
     * @param retailer the value for agent_retailer.retailer
     *
     * @mbggenerated
     */
    public void setRetailer(String retailer) {
        this.retailer = retailer == null ? null : retailer.trim();
    }
}