package com.model;

public class AssociatedFormat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column associated_format.format_id
     *
     * @mbggenerated
     */
    private Integer formatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column associated_format.format_name
     *
     * @mbggenerated
     */
    private String formatName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column associated_format.top_img
     *
     * @mbggenerated
     */
    private String topImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column associated_format.bottom_img
     *
     * @mbggenerated
     */
    private String bottomImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column associated_format.format_id
     *
     * @return the value of associated_format.format_id
     *
     * @mbggenerated
     */
    public Integer getFormatId() {
        return formatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column associated_format.format_id
     *
     * @param formatId the value for associated_format.format_id
     *
     * @mbggenerated
     */
    public void setFormatId(Integer formatId) {
        this.formatId = formatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column associated_format.format_name
     *
     * @return the value of associated_format.format_name
     *
     * @mbggenerated
     */
    public String getFormatName() {
        return formatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column associated_format.format_name
     *
     * @param formatName the value for associated_format.format_name
     *
     * @mbggenerated
     */
    public void setFormatName(String formatName) {
        this.formatName = formatName == null ? null : formatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column associated_format.top_img
     *
     * @return the value of associated_format.top_img
     *
     * @mbggenerated
     */
    public String getTopImg() {
        return topImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column associated_format.top_img
     *
     * @param topImg the value for associated_format.top_img
     *
     * @mbggenerated
     */
    public void setTopImg(String topImg) {
        this.topImg = topImg == null ? null : topImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column associated_format.bottom_img
     *
     * @return the value of associated_format.bottom_img
     *
     * @mbggenerated
     */
    public String getBottomImg() {
        return bottomImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column associated_format.bottom_img
     *
     * @param bottomImg the value for associated_format.bottom_img
     *
     * @mbggenerated
     */
    public void setBottomImg(String bottomImg) {
        this.bottomImg = bottomImg == null ? null : bottomImg.trim();
    }
}