package com.model;

import java.math.BigDecimal;

public class Freight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.destination
     *
     * @mbggenerated
     */
    private String destination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.first_weight
     *
     * @mbggenerated
     */
    private BigDecimal firstWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.extend_weight
     *
     * @mbggenerated
     */
    private BigDecimal extendWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.free_sum
     *
     * @mbggenerated
     */
    private BigDecimal freeSum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.destination
     *
     * @return the value of freight.destination
     *
     * @mbggenerated
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.destination
     *
     * @param destination the value for freight.destination
     *
     * @mbggenerated
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.first_weight
     *
     * @return the value of freight.first_weight
     *
     * @mbggenerated
     */
    public BigDecimal getFirstWeight() {
        return firstWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.first_weight
     *
     * @param firstWeight the value for freight.first_weight
     *
     * @mbggenerated
     */
    public void setFirstWeight(BigDecimal firstWeight) {
        this.firstWeight = firstWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.extend_weight
     *
     * @return the value of freight.extend_weight
     *
     * @mbggenerated
     */
    public BigDecimal getExtendWeight() {
        return extendWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.extend_weight
     *
     * @param extendWeight the value for freight.extend_weight
     *
     * @mbggenerated
     */
    public void setExtendWeight(BigDecimal extendWeight) {
        this.extendWeight = extendWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.free_sum
     *
     * @return the value of freight.free_sum
     *
     * @mbggenerated
     */
    public BigDecimal getFreeSum() {
        return freeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.free_sum
     *
     * @param freeSum the value for freight.free_sum
     *
     * @mbggenerated
     */
    public void setFreeSum(BigDecimal freeSum) {
        this.freeSum = freeSum;
    }
}