package com.model;

public class Invoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_id
     *
     * @mbggenerated
     */
    private Integer invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_title
     *
     * @mbggenerated
     */
    private String invoiceTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_content
     *
     * @mbggenerated
     */
    private String invoiceContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.merchant_no
     *
     * @mbggenerated
     */
    private String merchantNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_id
     *
     * @return the value of invoice.invoice_id
     *
     * @mbggenerated
     */
    public Integer getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_id
     *
     * @param invoiceId the value for invoice.invoice_id
     *
     * @mbggenerated
     */
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_title
     *
     * @return the value of invoice.invoice_title
     *
     * @mbggenerated
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_title
     *
     * @param invoiceTitle the value for invoice.invoice_title
     *
     * @mbggenerated
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_content
     *
     * @return the value of invoice.invoice_content
     *
     * @mbggenerated
     */
    public String getInvoiceContent() {
        return invoiceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_content
     *
     * @param invoiceContent the value for invoice.invoice_content
     *
     * @mbggenerated
     */
    public void setInvoiceContent(String invoiceContent) {
        this.invoiceContent = invoiceContent == null ? null : invoiceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.merchant_no
     *
     * @return the value of invoice.merchant_no
     *
     * @mbggenerated
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.merchant_no
     *
     * @param merchantNo the value for invoice.merchant_no
     *
     * @mbggenerated
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }
}