package com.model;

import java.math.BigDecimal;

public class Merchant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.merchant_no
     *
     * @mbggenerated
     */
    private String merchantNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.region
     *
     * @mbggenerated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.is_postpaid
     *
     * @mbggenerated
     */
    private String isPostpaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.min_sum
     *
     * @mbggenerated
     */
    private BigDecimal minSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.bonus_point
     *
     * @mbggenerated
     */
    private Integer bonusPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.salesman
     *
     * @mbggenerated
     */
    private String salesman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.role_no
     *
     * @mbggenerated
     */
    private Integer roleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.merchant_no
     *
     * @return the value of merchant.merchant_no
     *
     * @mbggenerated
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.merchant_no
     *
     * @param merchantNo the value for merchant.merchant_no
     *
     * @mbggenerated
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.name
     *
     * @return the value of merchant.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.name
     *
     * @param name the value for merchant.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.password
     *
     * @return the value of merchant.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.password
     *
     * @param password the value for merchant.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.address
     *
     * @return the value of merchant.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.address
     *
     * @param address the value for merchant.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.phone
     *
     * @return the value of merchant.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.phone
     *
     * @param phone the value for merchant.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.email
     *
     * @return the value of merchant.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.email
     *
     * @param email the value for merchant.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.region
     *
     * @return the value of merchant.region
     *
     * @mbggenerated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.region
     *
     * @param region the value for merchant.region
     *
     * @mbggenerated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.is_postpaid
     *
     * @return the value of merchant.is_postpaid
     *
     * @mbggenerated
     */
    public String getIsPostpaid() {
        return isPostpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.is_postpaid
     *
     * @param isPostpaid the value for merchant.is_postpaid
     *
     * @mbggenerated
     */
    public void setIsPostpaid(String isPostpaid) {
        this.isPostpaid = isPostpaid == null ? null : isPostpaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.discount
     *
     * @return the value of merchant.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.discount
     *
     * @param discount the value for merchant.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.min_sum
     *
     * @return the value of merchant.min_sum
     *
     * @mbggenerated
     */
    public BigDecimal getMinSum() {
        return minSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.min_sum
     *
     * @param minSum the value for merchant.min_sum
     *
     * @mbggenerated
     */
    public void setMinSum(BigDecimal minSum) {
        this.minSum = minSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.status
     *
     * @return the value of merchant.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.status
     *
     * @param status the value for merchant.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.bonus_point
     *
     * @return the value of merchant.bonus_point
     *
     * @mbggenerated
     */
    public Integer getBonusPoint() {
        return bonusPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.bonus_point
     *
     * @param bonusPoint the value for merchant.bonus_point
     *
     * @mbggenerated
     */
    public void setBonusPoint(Integer bonusPoint) {
        this.bonusPoint = bonusPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.salesman
     *
     * @return the value of merchant.salesman
     *
     * @mbggenerated
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.salesman
     *
     * @param salesman the value for merchant.salesman
     *
     * @mbggenerated
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.role_no
     *
     * @return the value of merchant.role_no
     *
     * @mbggenerated
     */
    public Integer getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.role_no
     *
     * @param roleNo the value for merchant.role_no
     *
     * @mbggenerated
     */
    public void setRoleNo(Integer roleNo) {
        this.roleNo = roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.role_name
     *
     * @return the value of merchant.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.role_name
     *
     * @param roleName the value for merchant.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant.remarks
     *
     * @return the value of merchant.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant.remarks
     *
     * @param remarks the value for merchant.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}