package com.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.product_total
     *
     * @mbggenerated
     */
    private BigDecimal productTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.freight
     *
     * @mbggenerated
     */
    private BigDecimal freight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.benifit
     *
     * @mbggenerated
     */
    private BigDecimal benifit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.invoice_tax
     *
     * @mbggenerated
     */
    private BigDecimal invoiceTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.order_sum
     *
     * @mbggenerated
     */
    private BigDecimal orderSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.merchant_no
     *
     * @mbggenerated
     */
    private String merchantNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.staff_id
     *
     * @mbggenerated
     */
    private String staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.consignee
     *
     * @mbggenerated
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.delivery_phone
     *
     * @mbggenerated
     */
    private String deliveryPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.delivery_addr
     *
     * @mbggenerated
     */
    private String deliveryAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.if_invoice
     *
     * @mbggenerated
     */
    private String ifInvoice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.invoice_title
     *
     * @mbggenerated
     */
    private String invoiceTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.invoice_content
     *
     * @mbggenerated
     */
    private String invoiceContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.logistics_co
     *
     * @mbggenerated
     */
    private String logisticsCo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.logistics_no
     *
     * @mbggenerated
     */
    private String logisticsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.order_time
     *
     * @mbggenerated
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.pay_time
     *
     * @mbggenerated
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.deliver_time
     *
     * @mbggenerated
     */
    private Date deliverTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.deal_time
     *
     * @mbggenerated
     */
    private Date dealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.cancel_time
     *
     * @mbggenerated
     */
    private Date cancelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.pay_mode
     *
     * @mbggenerated
     */
    private String payMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.trans_no
     *
     * @mbggenerated
     */
    private String transNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.order_no
     *
     * @return the value of order_list.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.order_no
     *
     * @param orderNo the value for order_list.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.type
     *
     * @return the value of order_list.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.type
     *
     * @param type the value for order_list.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.product_total
     *
     * @return the value of order_list.product_total
     *
     * @mbggenerated
     */
    public BigDecimal getProductTotal() {
        return productTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.product_total
     *
     * @param productTotal the value for order_list.product_total
     *
     * @mbggenerated
     */
    public void setProductTotal(BigDecimal productTotal) {
        this.productTotal = productTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.freight
     *
     * @return the value of order_list.freight
     *
     * @mbggenerated
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.freight
     *
     * @param freight the value for order_list.freight
     *
     * @mbggenerated
     */
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.benifit
     *
     * @return the value of order_list.benifit
     *
     * @mbggenerated
     */
    public BigDecimal getBenifit() {
        return benifit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.benifit
     *
     * @param benifit the value for order_list.benifit
     *
     * @mbggenerated
     */
    public void setBenifit(BigDecimal benifit) {
        this.benifit = benifit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.invoice_tax
     *
     * @return the value of order_list.invoice_tax
     *
     * @mbggenerated
     */
    public BigDecimal getInvoiceTax() {
        return invoiceTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.invoice_tax
     *
     * @param invoiceTax the value for order_list.invoice_tax
     *
     * @mbggenerated
     */
    public void setInvoiceTax(BigDecimal invoiceTax) {
        this.invoiceTax = invoiceTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.order_sum
     *
     * @return the value of order_list.order_sum
     *
     * @mbggenerated
     */
    public BigDecimal getOrderSum() {
        return orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.order_sum
     *
     * @param orderSum the value for order_list.order_sum
     *
     * @mbggenerated
     */
    public void setOrderSum(BigDecimal orderSum) {
        this.orderSum = orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.merchant_no
     *
     * @return the value of order_list.merchant_no
     *
     * @mbggenerated
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.merchant_no
     *
     * @param merchantNo the value for order_list.merchant_no
     *
     * @mbggenerated
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.staff_id
     *
     * @return the value of order_list.staff_id
     *
     * @mbggenerated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.staff_id
     *
     * @param staffId the value for order_list.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.consignee
     *
     * @return the value of order_list.consignee
     *
     * @mbggenerated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.consignee
     *
     * @param consignee the value for order_list.consignee
     *
     * @mbggenerated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.delivery_phone
     *
     * @return the value of order_list.delivery_phone
     *
     * @mbggenerated
     */
    public String getDeliveryPhone() {
        return deliveryPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.delivery_phone
     *
     * @param deliveryPhone the value for order_list.delivery_phone
     *
     * @mbggenerated
     */
    public void setDeliveryPhone(String deliveryPhone) {
        this.deliveryPhone = deliveryPhone == null ? null : deliveryPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.delivery_addr
     *
     * @return the value of order_list.delivery_addr
     *
     * @mbggenerated
     */
    public String getDeliveryAddr() {
        return deliveryAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.delivery_addr
     *
     * @param deliveryAddr the value for order_list.delivery_addr
     *
     * @mbggenerated
     */
    public void setDeliveryAddr(String deliveryAddr) {
        this.deliveryAddr = deliveryAddr == null ? null : deliveryAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.if_invoice
     *
     * @return the value of order_list.if_invoice
     *
     * @mbggenerated
     */
    public String getIfInvoice() {
        return ifInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.if_invoice
     *
     * @param ifInvoice the value for order_list.if_invoice
     *
     * @mbggenerated
     */
    public void setIfInvoice(String ifInvoice) {
        this.ifInvoice = ifInvoice == null ? null : ifInvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.invoice_title
     *
     * @return the value of order_list.invoice_title
     *
     * @mbggenerated
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.invoice_title
     *
     * @param invoiceTitle the value for order_list.invoice_title
     *
     * @mbggenerated
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.invoice_content
     *
     * @return the value of order_list.invoice_content
     *
     * @mbggenerated
     */
    public String getInvoiceContent() {
        return invoiceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.invoice_content
     *
     * @param invoiceContent the value for order_list.invoice_content
     *
     * @mbggenerated
     */
    public void setInvoiceContent(String invoiceContent) {
        this.invoiceContent = invoiceContent == null ? null : invoiceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.logistics_co
     *
     * @return the value of order_list.logistics_co
     *
     * @mbggenerated
     */
    public String getLogisticsCo() {
        return logisticsCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.logistics_co
     *
     * @param logisticsCo the value for order_list.logistics_co
     *
     * @mbggenerated
     */
    public void setLogisticsCo(String logisticsCo) {
        this.logisticsCo = logisticsCo == null ? null : logisticsCo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.logistics_no
     *
     * @return the value of order_list.logistics_no
     *
     * @mbggenerated
     */
    public String getLogisticsNo() {
        return logisticsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.logistics_no
     *
     * @param logisticsNo the value for order_list.logistics_no
     *
     * @mbggenerated
     */
    public void setLogisticsNo(String logisticsNo) {
        this.logisticsNo = logisticsNo == null ? null : logisticsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.order_time
     *
     * @return the value of order_list.order_time
     *
     * @mbggenerated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.order_time
     *
     * @param orderTime the value for order_list.order_time
     *
     * @mbggenerated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.pay_time
     *
     * @return the value of order_list.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.pay_time
     *
     * @param payTime the value for order_list.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.deliver_time
     *
     * @return the value of order_list.deliver_time
     *
     * @mbggenerated
     */
    public Date getDeliverTime() {
        return deliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.deliver_time
     *
     * @param deliverTime the value for order_list.deliver_time
     *
     * @mbggenerated
     */
    public void setDeliverTime(Date deliverTime) {
        this.deliverTime = deliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.deal_time
     *
     * @return the value of order_list.deal_time
     *
     * @mbggenerated
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.deal_time
     *
     * @param dealTime the value for order_list.deal_time
     *
     * @mbggenerated
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.cancel_time
     *
     * @return the value of order_list.cancel_time
     *
     * @mbggenerated
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.cancel_time
     *
     * @param cancelTime the value for order_list.cancel_time
     *
     * @mbggenerated
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.pay_mode
     *
     * @return the value of order_list.pay_mode
     *
     * @mbggenerated
     */
    public String getPayMode() {
        return payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.pay_mode
     *
     * @param payMode the value for order_list.pay_mode
     *
     * @mbggenerated
     */
    public void setPayMode(String payMode) {
        this.payMode = payMode == null ? null : payMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.trans_no
     *
     * @return the value of order_list.trans_no
     *
     * @mbggenerated
     */
    public String getTransNo() {
        return transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.trans_no
     *
     * @param transNo the value for order_list.trans_no
     *
     * @mbggenerated
     */
    public void setTransNo(String transNo) {
        this.transNo = transNo == null ? null : transNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.status
     *
     * @return the value of order_list.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.status
     *
     * @param status the value for order_list.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.remarks
     *
     * @return the value of order_list.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.remarks
     *
     * @param remarks the value for order_list.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}