package com.model;

import java.math.BigDecimal;

public class OrderItem extends OrderItemKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.prod_no
     *
     * @mbggenerated
     */
    private String prodNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.prod_desc
     *
     * @mbggenerated
     */
    private String prodDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.attr_name
     *
     * @mbggenerated
     */
    private String attrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.attr_desc
     *
     * @mbggenerated
     */
    private String attrDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.original_price
     *
     * @mbggenerated
     */
    private BigDecimal originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.discount_price
     *
     * @mbggenerated
     */
    private BigDecimal discountPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.prod_no
     *
     * @return the value of order_item.prod_no
     *
     * @mbggenerated
     */
    public String getProdNo() {
        return prodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.prod_no
     *
     * @param prodNo the value for order_item.prod_no
     *
     * @mbggenerated
     */
    public void setProdNo(String prodNo) {
        this.prodNo = prodNo == null ? null : prodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.prod_desc
     *
     * @return the value of order_item.prod_desc
     *
     * @mbggenerated
     */
    public String getProdDesc() {
        return prodDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.prod_desc
     *
     * @param prodDesc the value for order_item.prod_desc
     *
     * @mbggenerated
     */
    public void setProdDesc(String prodDesc) {
        this.prodDesc = prodDesc == null ? null : prodDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.attr_name
     *
     * @return the value of order_item.attr_name
     *
     * @mbggenerated
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.attr_name
     *
     * @param attrName the value for order_item.attr_name
     *
     * @mbggenerated
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.attr_desc
     *
     * @return the value of order_item.attr_desc
     *
     * @mbggenerated
     */
    public String getAttrDesc() {
        return attrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.attr_desc
     *
     * @param attrDesc the value for order_item.attr_desc
     *
     * @mbggenerated
     */
    public void setAttrDesc(String attrDesc) {
        this.attrDesc = attrDesc == null ? null : attrDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.image
     *
     * @return the value of order_item.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.image
     *
     * @param image the value for order_item.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.original_price
     *
     * @return the value of order_item.original_price
     *
     * @mbggenerated
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.original_price
     *
     * @param originalPrice the value for order_item.original_price
     *
     * @mbggenerated
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.discount_price
     *
     * @return the value of order_item.discount_price
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.discount_price
     *
     * @param discountPrice the value for order_item.discount_price
     *
     * @mbggenerated
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.quantity
     *
     * @return the value of order_item.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.quantity
     *
     * @param quantity the value for order_item.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}