package com.model;

import java.math.BigDecimal;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prod_no
     *
     * @mbggenerated
     */
    private String prodNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.min_price
     *
     * @mbggenerated
     */
    private BigDecimal minPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.max_price
     *
     * @mbggenerated
     */
    private BigDecimal maxPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.place
     *
     * @mbggenerated
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.serial_no
     *
     * @mbggenerated
     */
    private String serialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.spec
     *
     * @mbggenerated
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.series_no1
     *
     * @mbggenerated
     */
    private Integer seriesNo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.series_no2
     *
     * @mbggenerated
     */
    private Integer seriesNo2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.format_id
     *
     * @mbggenerated
     */
    private Integer formatId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prod_no
     *
     * @return the value of product.prod_no
     *
     * @mbggenerated
     */
    public String getProdNo() {
        return prodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prod_no
     *
     * @param prodNo the value for product.prod_no
     *
     * @mbggenerated
     */
    public void setProdNo(String prodNo) {
        this.prodNo = prodNo == null ? null : prodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.min_price
     *
     * @return the value of product.min_price
     *
     * @mbggenerated
     */
    public BigDecimal getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.min_price
     *
     * @param minPrice the value for product.min_price
     *
     * @mbggenerated
     */
    public void setMinPrice(BigDecimal minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.max_price
     *
     * @return the value of product.max_price
     *
     * @mbggenerated
     */
    public BigDecimal getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.max_price
     *
     * @param maxPrice the value for product.max_price
     *
     * @mbggenerated
     */
    public void setMaxPrice(BigDecimal maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.place
     *
     * @return the value of product.place
     *
     * @mbggenerated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.place
     *
     * @param place the value for product.place
     *
     * @mbggenerated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand
     *
     * @return the value of product.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand
     *
     * @param brand the value for product.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.serial_no
     *
     * @return the value of product.serial_no
     *
     * @mbggenerated
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.serial_no
     *
     * @param serialNo the value for product.serial_no
     *
     * @mbggenerated
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.spec
     *
     * @return the value of product.spec
     *
     * @mbggenerated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.spec
     *
     * @param spec the value for product.spec
     *
     * @mbggenerated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.series_no1
     *
     * @return the value of product.series_no1
     *
     * @mbggenerated
     */
    public Integer getSeriesNo1() {
        return seriesNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.series_no1
     *
     * @param seriesNo1 the value for product.series_no1
     *
     * @mbggenerated
     */
    public void setSeriesNo1(Integer seriesNo1) {
        this.seriesNo1 = seriesNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.series_no2
     *
     * @return the value of product.series_no2
     *
     * @mbggenerated
     */
    public Integer getSeriesNo2() {
        return seriesNo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.series_no2
     *
     * @param seriesNo2 the value for product.series_no2
     *
     * @mbggenerated
     */
    public void setSeriesNo2(Integer seriesNo2) {
        this.seriesNo2 = seriesNo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail
     *
     * @return the value of product.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail
     *
     * @param detail the value for product.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.format_id
     *
     * @return the value of product.format_id
     *
     * @mbggenerated
     */
    public Integer getFormatId() {
        return formatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.format_id
     *
     * @param formatId the value for product.format_id
     *
     * @mbggenerated
     */
    public void setFormatId(Integer formatId) {
        this.formatId = formatId;
    }
}