package com.model;

import java.math.BigDecimal;
import java.util.Date;

public class ProductSalesattr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.sku
     *
     * @mbggenerated
     */
    private String sku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.prod_no
     *
     * @mbggenerated
     */
    private String prodNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.attr_name
     *
     * @mbggenerated
     */
    private String attrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.stock_warn
     *
     * @mbggenerated
     */
    private Integer stockWarn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.is_inspect
     *
     * @mbggenerated
     */
    private String isInspect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.onsale_time
     *
     * @mbggenerated
     */
    private Date onsaleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_salesattr.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.sku
     *
     * @return the value of product_salesattr.sku
     *
     * @mbggenerated
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.sku
     *
     * @param sku the value for product_salesattr.sku
     *
     * @mbggenerated
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.prod_no
     *
     * @return the value of product_salesattr.prod_no
     *
     * @mbggenerated
     */
    public String getProdNo() {
        return prodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.prod_no
     *
     * @param prodNo the value for product_salesattr.prod_no
     *
     * @mbggenerated
     */
    public void setProdNo(String prodNo) {
        this.prodNo = prodNo == null ? null : prodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.attr_name
     *
     * @return the value of product_salesattr.attr_name
     *
     * @mbggenerated
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.attr_name
     *
     * @param attrName the value for product_salesattr.attr_name
     *
     * @mbggenerated
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.description
     *
     * @return the value of product_salesattr.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.description
     *
     * @param description the value for product_salesattr.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.image
     *
     * @return the value of product_salesattr.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.image
     *
     * @param image the value for product_salesattr.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.price
     *
     * @return the value of product_salesattr.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.price
     *
     * @param price the value for product_salesattr.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.stock
     *
     * @return the value of product_salesattr.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.stock
     *
     * @param stock the value for product_salesattr.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.stock_warn
     *
     * @return the value of product_salesattr.stock_warn
     *
     * @mbggenerated
     */
    public Integer getStockWarn() {
        return stockWarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.stock_warn
     *
     * @param stockWarn the value for product_salesattr.stock_warn
     *
     * @mbggenerated
     */
    public void setStockWarn(Integer stockWarn) {
        this.stockWarn = stockWarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.is_inspect
     *
     * @return the value of product_salesattr.is_inspect
     *
     * @mbggenerated
     */
    public String getIsInspect() {
        return isInspect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.is_inspect
     *
     * @param isInspect the value for product_salesattr.is_inspect
     *
     * @mbggenerated
     */
    public void setIsInspect(String isInspect) {
        this.isInspect = isInspect == null ? null : isInspect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.onsale_time
     *
     * @return the value of product_salesattr.onsale_time
     *
     * @mbggenerated
     */
    public Date getOnsaleTime() {
        return onsaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.onsale_time
     *
     * @param onsaleTime the value for product_salesattr.onsale_time
     *
     * @mbggenerated
     */
    public void setOnsaleTime(Date onsaleTime) {
        this.onsaleTime = onsaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_salesattr.status
     *
     * @return the value of product_salesattr.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_salesattr.status
     *
     * @param status the value for product_salesattr.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}