package com.model;

import java.util.Date;

public class ReviewHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_history.t_name
     *
     * @mbggenerated
     */
    private String tName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_history.uni_key
     *
     * @mbggenerated
     */
    private String uniKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_history.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_history.st_name
     *
     * @mbggenerated
     */
    private String stName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_history.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_history.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_history.op_name
     *
     * @mbggenerated
     */
    private String opName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_history.op_role
     *
     * @mbggenerated
     */
    private String opRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_history.op_time
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_history.t_name
     *
     * @return the value of review_history.t_name
     *
     * @mbggenerated
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_history.t_name
     *
     * @param tName the value for review_history.t_name
     *
     * @mbggenerated
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_history.uni_key
     *
     * @return the value of review_history.uni_key
     *
     * @mbggenerated
     */
    public String getUniKey() {
        return uniKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_history.uni_key
     *
     * @param uniKey the value for review_history.uni_key
     *
     * @mbggenerated
     */
    public void setUniKey(String uniKey) {
        this.uniKey = uniKey == null ? null : uniKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_history.status
     *
     * @return the value of review_history.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_history.status
     *
     * @param status the value for review_history.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_history.st_name
     *
     * @return the value of review_history.st_name
     *
     * @mbggenerated
     */
    public String getStName() {
        return stName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_history.st_name
     *
     * @param stName the value for review_history.st_name
     *
     * @mbggenerated
     */
    public void setStName(String stName) {
        this.stName = stName == null ? null : stName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_history.remarks
     *
     * @return the value of review_history.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_history.remarks
     *
     * @param remarks the value for review_history.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_history.operator
     *
     * @return the value of review_history.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_history.operator
     *
     * @param operator the value for review_history.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_history.op_name
     *
     * @return the value of review_history.op_name
     *
     * @mbggenerated
     */
    public String getOpName() {
        return opName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_history.op_name
     *
     * @param opName the value for review_history.op_name
     *
     * @mbggenerated
     */
    public void setOpName(String opName) {
        this.opName = opName == null ? null : opName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_history.op_role
     *
     * @return the value of review_history.op_role
     *
     * @mbggenerated
     */
    public String getOpRole() {
        return opRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_history.op_role
     *
     * @param opRole the value for review_history.op_role
     *
     * @mbggenerated
     */
    public void setOpRole(String opRole) {
        this.opRole = opRole == null ? null : opRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_history.op_time
     *
     * @return the value of review_history.op_time
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_history.op_time
     *
     * @param opTime the value for review_history.op_time
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }
}