package com.model;

import java.math.BigDecimal;

public class SalesPromotion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_promotion.prom_id
     *
     * @mbggenerated
     */
    private Integer promId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_promotion.prom_name
     *
     * @mbggenerated
     */
    private String promName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_promotion.sum
     *
     * @mbggenerated
     */
    private BigDecimal sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_promotion.off
     *
     * @mbggenerated
     */
    private BigDecimal off;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_promotion.prom_id
     *
     * @return the value of sales_promotion.prom_id
     *
     * @mbggenerated
     */
    public Integer getPromId() {
        return promId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_promotion.prom_id
     *
     * @param promId the value for sales_promotion.prom_id
     *
     * @mbggenerated
     */
    public void setPromId(Integer promId) {
        this.promId = promId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_promotion.prom_name
     *
     * @return the value of sales_promotion.prom_name
     *
     * @mbggenerated
     */
    public String getPromName() {
        return promName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_promotion.prom_name
     *
     * @param promName the value for sales_promotion.prom_name
     *
     * @mbggenerated
     */
    public void setPromName(String promName) {
        this.promName = promName == null ? null : promName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_promotion.sum
     *
     * @return the value of sales_promotion.sum
     *
     * @mbggenerated
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_promotion.sum
     *
     * @param sum the value for sales_promotion.sum
     *
     * @mbggenerated
     */
    public void setSum(BigDecimal sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_promotion.off
     *
     * @return the value of sales_promotion.off
     *
     * @mbggenerated
     */
    public BigDecimal getOff() {
        return off;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_promotion.off
     *
     * @param off the value for sales_promotion.off
     *
     * @mbggenerated
     */
    public void setOff(BigDecimal off) {
        this.off = off;
    }
}