package com.model;

public class Series {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column series.series_id
     *
     * @mbggenerated
     */
    private Integer seriesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column series.series_name
     *
     * @mbggenerated
     */
    private String seriesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column series.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column series.series_id
     *
     * @return the value of series.series_id
     *
     * @mbggenerated
     */
    public Integer getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column series.series_id
     *
     * @param seriesId the value for series.series_id
     *
     * @mbggenerated
     */
    public void setSeriesId(Integer seriesId) {
        this.seriesId = seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column series.series_name
     *
     * @return the value of series.series_name
     *
     * @mbggenerated
     */
    public String getSeriesName() {
        return seriesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column series.series_name
     *
     * @param seriesName the value for series.series_name
     *
     * @mbggenerated
     */
    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName == null ? null : seriesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column series.brand_id
     *
     * @return the value of series.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column series.brand_id
     *
     * @param brandId the value for series.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }
}