package com.model;

public class SkuSalesprom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_salesprom.sku
     *
     * @mbggenerated
     */
    private String sku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_salesprom.prom_id
     *
     * @mbggenerated
     */
    private Integer promId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_salesprom.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_salesprom.sku
     *
     * @return the value of sku_salesprom.sku
     *
     * @mbggenerated
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_salesprom.sku
     *
     * @param sku the value for sku_salesprom.sku
     *
     * @mbggenerated
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_salesprom.prom_id
     *
     * @return the value of sku_salesprom.prom_id
     *
     * @mbggenerated
     */
    public Integer getPromId() {
        return promId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_salesprom.prom_id
     *
     * @param promId the value for sku_salesprom.prom_id
     *
     * @mbggenerated
     */
    public void setPromId(Integer promId) {
        this.promId = promId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_salesprom.status
     *
     * @return the value of sku_salesprom.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_salesprom.status
     *
     * @param status the value for sku_salesprom.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}