package com.model;

import java.math.BigDecimal;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_no
     *
     * @mbggenerated
     */
    private String staffNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.id_no
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.id_img
     *
     * @mbggenerated
     */
    private String idImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.dept_no
     *
     * @mbggenerated
     */
    private Integer deptNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.dept_name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.basic_salary
     *
     * @mbggenerated
     */
    private BigDecimal basicSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.travel_allowance
     *
     * @mbggenerated
     */
    private BigDecimal travelAllowance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.meal_allowance
     *
     * @mbggenerated
     */
    private BigDecimal mealAllowance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.overtime_allowance
     *
     * @mbggenerated
     */
    private BigDecimal overtimeAllowance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.commission
     *
     * @mbggenerated
     */
    private BigDecimal commission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.role_no
     *
     * @mbggenerated
     */
    private Integer roleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_no
     *
     * @return the value of staff.staff_no
     *
     * @mbggenerated
     */
    public String getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_no
     *
     * @param staffNo the value for staff.staff_no
     *
     * @mbggenerated
     */
    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo == null ? null : staffNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.name
     *
     * @return the value of staff.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.name
     *
     * @param name the value for staff.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.password
     *
     * @return the value of staff.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.password
     *
     * @param password the value for staff.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.address
     *
     * @return the value of staff.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.address
     *
     * @param address the value for staff.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.phone
     *
     * @return the value of staff.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.phone
     *
     * @param phone the value for staff.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.email
     *
     * @return the value of staff.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.email
     *
     * @param email the value for staff.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.id_no
     *
     * @return the value of staff.id_no
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.id_no
     *
     * @param idNo the value for staff.id_no
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.id_img
     *
     * @return the value of staff.id_img
     *
     * @mbggenerated
     */
    public String getIdImg() {
        return idImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.id_img
     *
     * @param idImg the value for staff.id_img
     *
     * @mbggenerated
     */
    public void setIdImg(String idImg) {
        this.idImg = idImg == null ? null : idImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.dept_no
     *
     * @return the value of staff.dept_no
     *
     * @mbggenerated
     */
    public Integer getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.dept_no
     *
     * @param deptNo the value for staff.dept_no
     *
     * @mbggenerated
     */
    public void setDeptNo(Integer deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.dept_name
     *
     * @return the value of staff.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.dept_name
     *
     * @param deptName the value for staff.dept_name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.basic_salary
     *
     * @return the value of staff.basic_salary
     *
     * @mbggenerated
     */
    public BigDecimal getBasicSalary() {
        return basicSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.basic_salary
     *
     * @param basicSalary the value for staff.basic_salary
     *
     * @mbggenerated
     */
    public void setBasicSalary(BigDecimal basicSalary) {
        this.basicSalary = basicSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.travel_allowance
     *
     * @return the value of staff.travel_allowance
     *
     * @mbggenerated
     */
    public BigDecimal getTravelAllowance() {
        return travelAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.travel_allowance
     *
     * @param travelAllowance the value for staff.travel_allowance
     *
     * @mbggenerated
     */
    public void setTravelAllowance(BigDecimal travelAllowance) {
        this.travelAllowance = travelAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.meal_allowance
     *
     * @return the value of staff.meal_allowance
     *
     * @mbggenerated
     */
    public BigDecimal getMealAllowance() {
        return mealAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.meal_allowance
     *
     * @param mealAllowance the value for staff.meal_allowance
     *
     * @mbggenerated
     */
    public void setMealAllowance(BigDecimal mealAllowance) {
        this.mealAllowance = mealAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.overtime_allowance
     *
     * @return the value of staff.overtime_allowance
     *
     * @mbggenerated
     */
    public BigDecimal getOvertimeAllowance() {
        return overtimeAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.overtime_allowance
     *
     * @param overtimeAllowance the value for staff.overtime_allowance
     *
     * @mbggenerated
     */
    public void setOvertimeAllowance(BigDecimal overtimeAllowance) {
        this.overtimeAllowance = overtimeAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.commission
     *
     * @return the value of staff.commission
     *
     * @mbggenerated
     */
    public BigDecimal getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.commission
     *
     * @param commission the value for staff.commission
     *
     * @mbggenerated
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.role_no
     *
     * @return the value of staff.role_no
     *
     * @mbggenerated
     */
    public Integer getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.role_no
     *
     * @param roleNo the value for staff.role_no
     *
     * @mbggenerated
     */
    public void setRoleNo(Integer roleNo) {
        this.roleNo = roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.role_name
     *
     * @return the value of staff.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.role_name
     *
     * @param roleName the value for staff.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}