package com.model;

public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_path
     *
     * @mbggenerated
     */
    private String videoPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_path
     *
     * @return the value of video.video_path
     *
     * @mbggenerated
     */
    public String getVideoPath() {
        return videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_path
     *
     * @param videoPath the value for video.video_path
     *
     * @mbggenerated
     */
    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath == null ? null : videoPath.trim();
    }
}