package com.dao;

import com.model.Campaign;
import com.model.CampaignExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CampaignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int countByExample(CampaignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int deleteByExample(CampaignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int insert(Campaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int insertSelective(Campaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    List<Campaign> selectByExample(CampaignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Campaign record, @Param("example") CampaignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Campaign record, @Param("example") CampaignExample example);
}