package com.dao;

import com.model.CartItem;
import com.model.CartItemExample;
import com.model.CartItemKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    int countByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    int deleteByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CartItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    int insert(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    int insertSelective(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    List<CartItem> selectByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    CartItem selectByPrimaryKey(CartItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CartItem record, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CartItem record, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CartItem record);
}