package com.dao;

import com.model.DeliveryAddress;
import com.model.DeliveryAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeliveryAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    int countByExample(DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    int deleteByExample(DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    int insert(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    int insertSelective(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    List<DeliveryAddress> selectByExample(DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    DeliveryAddress selectByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeliveryAddress record, @Param("example") DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeliveryAddress record, @Param("example") DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeliveryAddress record);
}