package com.dao;

import com.model.Freight;
import com.model.FreightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FreightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight
     *
     * @mbggenerated
     */
    int countByExample(FreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight
     *
     * @mbggenerated
     */
    int deleteByExample(FreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight
     *
     * @mbggenerated
     */
    int insert(Freight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight
     *
     * @mbggenerated
     */
    int insertSelective(Freight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight
     *
     * @mbggenerated
     */
    List<Freight> selectByExample(FreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Freight record, @Param("example") FreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Freight record, @Param("example") FreightExample example);
}