package com.dao;

import com.model.Introduction;
import com.model.IntroductionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IntroductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int countByExample(IntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int deleteByExample(IntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int insert(Introduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int insertSelective(Introduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    List<Introduction> selectByExample(IntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Introduction record, @Param("example") IntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Introduction record, @Param("example") IntroductionExample example);
}