package com.dao;

import com.model.LogisticsCompany;
import com.model.LogisticsCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogisticsCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    int countByExample(LogisticsCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    int deleteByExample(LogisticsCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer company);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    int insert(LogisticsCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    int insertSelective(LogisticsCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    List<LogisticsCompany> selectByExample(LogisticsCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    LogisticsCompany selectByPrimaryKey(Integer company);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LogisticsCompany record, @Param("example") LogisticsCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LogisticsCompany record, @Param("example") LogisticsCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogisticsCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogisticsCompany record);
}