package com.dao;

import com.model.OrderType;
import com.model.OrderTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    int countByExample(OrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    int deleteByExample(OrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    int insert(OrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    int insertSelective(OrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    List<OrderType> selectByExample(OrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    OrderType selectByPrimaryKey(Integer type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderType record, @Param("example") OrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderType record, @Param("example") OrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderType record);
}