package com.dao;

import com.model.OrderList;
import com.model.OrderListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    int countByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    int deleteByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    int insert(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    int insertSelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    List<OrderList> selectByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    OrderList selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderList record, @Param("example") OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderList record, @Param("example") OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderList record);
}