package com.dao;

import com.model.ReviewHistory;
import com.model.ReviewHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReviewHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_history
     *
     * @mbggenerated
     */
    int countByExample(ReviewHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_history
     *
     * @mbggenerated
     */
    int deleteByExample(ReviewHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_history
     *
     * @mbggenerated
     */
    int insert(ReviewHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_history
     *
     * @mbggenerated
     */
    int insertSelective(ReviewHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_history
     *
     * @mbggenerated
     */
    List<ReviewHistory> selectByExample(ReviewHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_history
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReviewHistory record, @Param("example") ReviewHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_history
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReviewHistory record, @Param("example") ReviewHistoryExample example);
}