package com.dao;

import com.model.Series;
import com.model.SeriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    int countByExample(SeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    int deleteByExample(SeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer seriesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    int insert(Series record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    int insertSelective(Series record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    List<Series> selectByExample(SeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    Series selectByPrimaryKey(Integer seriesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Series record, @Param("example") SeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Series record, @Param("example") SeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Series record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Series record);
}